import { InfluenceEdge, Thinker } from "./types";

// Generated by scripts/importWikidataBatch.ts from explicit Wikidata statements.
export const WIKIDATA_BATCH_PROVENANCE = [
  {
    "atlasId": "john_warnock",
    "wikidataId": "Q1344392",
    "sourceUrl": "https://www.wikidata.org/wiki/Q1344392"
  },
  {
    "atlasId": "vannevar_bush",
    "wikidataId": "Q299595",
    "sourceUrl": "https://www.wikidata.org/wiki/Q299595"
  },
  {
    "atlasId": "john_polkinghorne",
    "wikidataId": "Q726724",
    "sourceUrl": "https://www.wikidata.org/wiki/Q726724"
  }
] as const;

export const WIKIDATA_IMPORTED_PEOPLE: Thinker[] = [
  {"id":"john_warnock","name":"John Warnock","birth":1940,"death":2023,"fields":["Computing"],"subfields":["computing","computer program","software engineering"],"region":"United States","era":"Modernism","movement":null,"bridge_score":3,"works":["PDF"],"influenced":[],"notes":"American computer scientist, inventor and technology businessman (1940–2023)."},
  {"id":"vannevar_bush","name":"Vannevar Bush","birth":1890,"death":1974,"fields":["Computing"],"subfields":["futures studies"],"region":"United States","era":"19th Century","movement":null,"bridge_score":3,"works":["Memex"],"influenced":[],"notes":"American electrical engineer and science administrator (1890–1974)."},
  {"id":"john_polkinghorne","name":"John Polkinghorne","birth":1930,"death":2021,"fields":["Mathematics"],"subfields":["theology","physics","mathematical physics"],"region":"United Kingdom","era":"Modernism","movement":null,"bridge_score":3,"works":["Faith, Science and Understanding","The Way the World Is: Christian Perspective of a Scientist","Science and Theology","Questions of Truth","Quantum Theory: A Very Short Introduction"],"influenced":[],"notes":"physicist, theologian and anglican priest (1930–2021)."},
];

export const WIKIDATA_IMPORTED_EDGES: InfluenceEdge[] = [
  {"source":"kolmogorov","target":"hoare","type":"Mentorship","strength":5,"note":"Wikidata P184 explicitly records the advisor/student relationship.","confidence":0.95,"sourceClaims":["https://www.wikidata.org/wiki/Q92602"],"status":"accepted"},
  {"source":"shannon","target":"sutherland","type":"Mentorship","strength":5,"note":"Wikidata P184 explicitly records the advisor/student relationship.","confidence":0.95,"sourceClaims":["https://www.wikidata.org/wiki/Q62866"],"status":"accepted"},
  {"source":"sutherland","target":"john_warnock","type":"Mentorship","strength":5,"note":"Wikidata P185 explicitly records the advisor/student relationship.","confidence":0.95,"sourceClaims":["https://www.wikidata.org/wiki/Q62866"],"status":"accepted"},
  {"source":"vannevar_bush","target":"engelbart","type":"Influence","strength":4,"note":"Wikidata P737 explicitly records this influence relationship.","confidence":0.9,"sourceClaims":["https://www.wikidata.org/wiki/Q92614"],"status":"accepted"},
  {"source":"sutherland","target":"engelbart","type":"Influence","strength":4,"note":"Wikidata P737 explicitly records this influence relationship.","confidence":0.9,"sourceClaims":["https://www.wikidata.org/wiki/Q92614"],"status":"accepted"},
  {"source":"dirac","target":"salam","type":"Influence","strength":4,"note":"Wikidata P737 explicitly records this influence relationship.","confidence":0.9,"sourceClaims":["https://www.wikidata.org/wiki/Q28189"],"status":"accepted"},
  {"source":"salam","target":"john_polkinghorne","type":"Mentorship","strength":5,"note":"Wikidata P185 explicitly records the advisor/student relationship.","confidence":0.95,"sourceClaims":["https://www.wikidata.org/wiki/Q28189"],"status":"accepted"},
  {"source":"bardeen_john","target":"schrieffer_john","type":"Mentorship","strength":5,"note":"Wikidata P185 explicitly records the advisor/student relationship.","confidence":0.95,"sourceClaims":["https://www.wikidata.org/wiki/Q949"],"status":"accepted"},
  {"source":"vannevar_bush","target":"shannon","type":"Influence","strength":4,"note":"Wikidata P737 explicitly records this influence relationship.","confidence":0.9,"sourceClaims":["https://www.wikidata.org/wiki/Q92760"],"status":"accepted"},
  {"source":"dirac","target":"john_polkinghorne","type":"Mentorship","strength":5,"note":"Wikidata P185 explicitly records the advisor/student relationship.","confidence":0.95,"sourceClaims":["https://www.wikidata.org/wiki/Q47480"],"status":"accepted"},
];
