import { InfluenceEdge, Thinker } from "./types";

// Generated by scripts/importWikidataBatch.ts from explicit Wikidata statements.
export const WIKIDATA_BATCH_PROVENANCE = [
  {
    "atlasId": "al_hilli",
    "wikidataId": "Q290506",
    "sourceUrl": "https://www.wikidata.org/wiki/Q290506"
  }
] as const;

export const WIKIDATA_IMPORTED_PEOPLE: Thinker[] = [
  {"id":"al_hilli","name":"Al-Hilli","birth":1250,"death":1325,"fields":["Logic"],"subfields":["fiqh","Usul al-fiqh","science of hadith"],"region":"Abbasid Caliphate/Ilkhanate","era":"Islamic Golden Age","movement":"Islamic Golden Age","bridge_score":3,"works":["Minhaj al-karamah","Tadhkirat al-Fuqahā","Nahj Al Haq Va Kashf Al Sedq","Kashf al-Yaqin","Al-Nāfiʻ yawm al-ḥashr fī sharḥ al-Bāb al-ḥādī ʻashar"],"influenced":[],"notes":"Iraqi Islamic theologian and scholar (1250-1325)."},
];

export const WIKIDATA_IMPORTED_EDGES: InfluenceEdge[] = [
  {"source":"avicenna","target":"tusi","type":"Influence","strength":4,"note":"Wikidata P737 explicitly records this influence relationship.","confidence":0.9,"sourceClaims":["https://www.wikidata.org/wiki/Q302835"],"status":"accepted"},
  {"source":"al_razi_theologian","target":"tusi","type":"Influence","strength":4,"note":"Wikidata P737 explicitly records this influence relationship.","confidence":0.9,"sourceClaims":["https://www.wikidata.org/wiki/Q302835"],"status":"accepted"},
  {"source":"tusi","target":"al_hilli","type":"Mentorship","strength":5,"note":"Wikidata P185 explicitly records the advisor/student relationship.","confidence":0.95,"sourceClaims":["https://www.wikidata.org/wiki/Q302835"],"status":"accepted"},
  {"source":"al_farabi","target":"suhrawardi","type":"Influence","strength":4,"note":"Wikidata P737 explicitly records this influence relationship.","confidence":0.9,"sourceClaims":["https://www.wikidata.org/wiki/Q282883"],"status":"accepted"},
];
