import { CanonicalThread } from "./types";

export const CANONICAL_THREADS: CanonicalThread[] = [
  {
    id: "logic-to-computation",
    title: "Logic To Computation",
    field: "Logic / Computing",
    purpose: "Follow formal reasoning as it becomes symbolic logic, computability, and information theory.",
    people: ["aristotle", "chrysippus", "leibniz", "boole", "frege", "russell", "godel", "church", "turing", "von_neumann", "shannon"],
    concepts: ["syllogism", "propositional logic", "binary arithmetic", "Boolean algebra", "logicism", "incompleteness", "lambda calculus", "universal computation", "information entropy"],
    edgeTypes: ["Influence", "Indirect influence", "Mentorship"],
    confidence: "medium",
  },
  {
    id: "metaphysics-to-idealism",
    title: "Metaphysics To Idealism",
    field: "Philosophy",
    purpose: "Trace being, substance, reason, and mind from classical metaphysics into German Idealism.",
    people: ["plato", "aristotle", "aquinas", "descartes", "spinoza", "leibniz", "kant", "hegel"],
    concepts: ["forms", "substance", "scholastic synthesis", "rationalism", "monism", "transcendental idealism", "dialectic"],
    edgeTypes: ["Influence", "Indirect influence", "Transmission"],
    confidence: "medium",
  },
  {
    id: "empiricism-to-pragmatism",
    title: "Empiricism To Pragmatism",
    field: "Philosophy / Psychology",
    purpose: "Follow sensory empiricism and skepticism into practical consequences, instrumentalism, and neo-pragmatism.",
    people: ["bacon", "locke", "hume", "mill", "peirce", "james", "dewey", "rorty"],
    concepts: ["induction", "tabula rasa", "skepticism", "liberty", "pragmatic maxim", "functional psychology", "instrumentalism", "anti-foundationalism"],
    edgeTypes: ["Influence", "Indirect influence", "Collaboration"],
    confidence: "needs-review",
  },
  {
    id: "existentialism-to-poststructuralism",
    title: "Existentialism To Poststructuralism",
    field: "Philosophy / Critical Theory",
    purpose: "Trace existential freedom, genealogy, deconstruction, and performativity across modern continental philosophy.",
    people: ["kierkegaard", "nietzsche", "heidegger", "sartre", "simone_de_beauvoir", "foucault", "derrida", "butler"],
    concepts: ["anxiety", "nihilism", "Dasein", "existence precedes essence", "existential feminism", "power-knowledge", "deconstruction", "performativity"],
    edgeTypes: ["Influence", "Indirect influence", "Parallel"],
    confidence: "needs-review",
  },
  {
    id: "probability-to-causality",
    title: "Probability To Causality",
    field: "Mathematics / AI",
    purpose: "Follow uncertainty from chance problems into statistics, information theory, and causal machine learning.",
    people: ["pascal", "fermat", "bayes", "laplace", "gauss", "fisher_ronald", "kolmogorov", "shannon", "pearl_judea"],
    concepts: ["probability", "inverse probability", "least squares", "statistical inference", "axiomatized probability", "information", "causal graphs"],
    edgeTypes: ["Influence", "Indirect influence", "Parallel"],
    confidence: "needs-review",
  },
  {
    id: "geometry-to-topology",
    title: "Geometry To Topology",
    field: "Mathematics",
    purpose: "Follow geometry from axiomatic constructions through coordinates, manifolds, topology, and 3-manifold geometrization.",
    people: ["euclid", "descartes", "gauss", "riemann", "poincare", "hilbert", "noether", "atiyah", "thurston", "perelman"],
    concepts: ["axiomatic geometry", "analytic geometry", "curvature", "Riemannian manifolds", "topology", "axiomatization", "abstract algebra", "K-theory", "geometrization", "Ricci flow"],
    edgeTypes: ["Influence", "Indirect influence", "Mentorship"],
    confidence: "needs-review",
  },
  {
    id: "calculus-to-analysis",
    title: "Calculus To Analysis",
    field: "Mathematics",
    purpose: "Trace infinitesimal methods from ancient exhaustion through calculus, spectral analysis, rigor, and complex analysis.",
    people: ["archimedes", "newton", "leibniz", "euler", "fourier", "cauchy", "weierstrass", "riemann"],
    concepts: ["method of exhaustion", "fluxions", "differential notation", "analysis", "Fourier series", "limits", "epsilon-delta rigor", "complex manifolds"],
    edgeTypes: ["Influence", "Indirect influence", "Parallel"],
    confidence: "needs-review",
  },
  {
    id: "computation-foundations",
    title: "Computation Foundations",
    field: "Logic / Computing",
    purpose: "Trace formal calculation from symbolic logic through undecidability, lambda calculus, stored-program architecture, and information theory.",
    people: ["leibniz", "boole", "frege", "hilbert", "godel", "church", "turing", "von_neumann", "shannon"],
    concepts: ["binary arithmetic", "Boolean algebra", "predicate logic", "formalism", "incompleteness", "lambda calculus", "universal computation", "stored program", "information entropy"],
    edgeTypes: ["Influence", "Indirect influence", "Mentorship"],
    confidence: "medium",
  },
  {
    id: "neural-networks",
    title: "Neural Networks",
    field: "Computing / Cognitive Science",
    purpose: "Trace the path from neural logic and learning rules into perceptrons and deep learning.",
    people: ["mcculloch", "pitts", "hebb", "rosenblatt", "minsky", "rumelhart", "hinton", "lecun", "bengio"],
    concepts: ["threshold neuron", "Hebbian learning", "perceptron", "connectionism", "backpropagation", "deep learning"],
    edgeTypes: ["Collaboration", "Influence", "Indirect influence"],
    confidence: "medium",
  },
  {
    id: "language-and-cognition",
    title: "Language And Cognition",
    field: "Linguistics / Psychology",
    purpose: "Compare formal grammar, symbolic cognition, and embodied/cognitive linguistics.",
    people: ["saussure", "chomsky", "fodor", "pinker", "lakoff", "hofstadter"],
    concepts: ["structural linguistics", "generative grammar", "language of thought", "language acquisition", "conceptual metaphor", "analogy"],
    edgeTypes: ["Influence", "Parallel", "Indirect influence"],
    confidence: "needs-review",
  },
  {
    id: "quantum-field-thread",
    title: "Quantum Field Thread",
    field: "Physics",
    purpose: "Follow quantum mechanics through field theory, diagrams, renormalization, and unification.",
    people: ["planck", "einstein", "bohr", "heisenberg", "schrodinger", "dirac", "feynman", "dyson", "weinberg", "witten"],
    concepts: ["quanta", "relativity", "Copenhagen interpretation", "matrix mechanics", "wave mechanics", "QED", "renormalization", "electroweak theory", "string theory"],
    edgeTypes: ["Influence", "Indirect influence", "Collaboration"],
    confidence: "medium",
  },
  {
    id: "evolution-to-genomics",
    title: "Evolution To Genomics",
    field: "Biology",
    purpose: "Connect natural history, evolutionary theory, genetics, molecular biology, and gene editing.",
    people: ["aristotle", "linnaeus", "darwin", "mendel", "morgan_th", "fisher_ronald", "haldane", "rosalind_franklin", "watson_crick", "sanger_fred", "doudna", "venter"],
    concepts: ["classification", "natural selection", "inheritance", "chromosomes", "population genetics", "DNA structure", "sequencing", "CRISPR", "genomics"],
    edgeTypes: ["Influence", "Indirect influence", "Collaboration"],
    confidence: "needs-review",
  },
  {
    id: "liberalism-and-capabilities",
    title: "Liberalism And Capabilities",
    field: "Political Thought / Economics",
    purpose: "Trace liberty, justice, political economy, and human capability debates.",
    people: ["hobbes", "locke", "rousseau", "smith", "mill", "rawls", "sen", "nussbaum"],
    concepts: ["social contract", "natural rights", "political economy", "liberty", "justice as fairness", "capabilities"],
    edgeTypes: ["Influence", "Indirect influence", "Collaboration"],
    confidence: "needs-review",
  },
  {
    id: "communication-networks",
    title: "Communication Networks",
    field: "Engineering / Computing",
    purpose: "Follow media and signal systems from printing through information theory into packet networks and the web.",
    people: ["gutenberg", "nyquist", "shannon", "cerf", "metcalfe", "berners_lee"],
    concepts: ["printing", "sampling", "channel capacity", "packet networking", "Ethernet", "World Wide Web"],
    edgeTypes: ["Influence", "Indirect influence"],
    confidence: "medium",
  },
];
